### ISSUE TITLE
app_version.h not found?

### ISSUE THREAD

**Issue by Meai1** [dghilardi/RustEditor#3]
I did your installation steps but your plugin wont compile, it doesnt find: 
# include <app/app_version.h>

**Comment by dghilardi** [comment]
Hi Meai1,
that seams pretty strange to me... may I ask you what version of qtcreator are you using (and from where you downloaded the code)?
The file you can't find should be located in `${QTC_BUILD}/src/app/app_version.h`
Here I report the detailed steps I followed to build qtcreator from source

``` bash
git clone https://github.com/qtproject/qt-creator.git qtcreator-git
cd qtcreator-git
cd ..
mkdir build && cd $_
qmake -r CONFIG+=debug ../qtcreator-git/qtcreator.pro
make -j4
```

hope it helps

DG

**Comment by Meai1** [comment]
I downloaded the qtcreator code from github via git clone, i dont think
that i compiled qtcreator wrong or anything. It produced an executable just
fine.
But when I try to compile your plugin it doesnt work with the mentioned
problem

Do i have to have a specific qt maybe? I have 5.6.0 and i disabled all the
QT_Quick and qt_android stuff

idk if I'm going to try that

2016-04-09 12:30 GMT+02:00 Davide Ghilardi notifications@github.com:

**Comment by dghilardi** [comment]
I don't think is a problem related to qt libraries since the required header belongs to qt-creator itself.
If you can't find that file I suggest you to try to compile the code at the previous commit (8e4401d) since it doesn't require that header.
Anyway I'll remove that include asap to be sure it won't cause trouble anymore...

**Comment by dghilardi** [comment]
The plugin does not depend on that header anymore
