### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by Mte90** [dghilardi/RustEditor#4]
there is written in the readme to compile but what are the correct commands?

**Comment by dghilardi** [comment]
Hi,
I've just added a subsection to the readme with the description of the compilation process, now it should be clearer.

DG

**Comment by Mte90** [comment]
To install on debian I download the source code of qtcreator from debian packages, next i followed the instructions only that rusteditor command to compile is different:
`qmake -r CONFIG+=release ../RustEditor/rusteditor.pro "QTC_SOURCE=$(pwd)/../qt-creator-opensource-src-4.0.1/" "QTC_BUILD=/usr/lib/x86_64-linux-gnu/qtcreator/" "QTC_MAJOR=4" "QTC_MINOR=0"`

The problem that the compile installed the plugin in a folder lib/qtcreator/plugins but on /usr/lib/x86_64-linux-gnu/qtcreator/ there is already a folder plugins.
So after the compile I move the libRustEditor.so in that folder and now is working :-)

**Comment by Mte90** [comment]
Now i have the panel in the settings, for Rust source i used /usr/lib/rustlib/x86_64-unknown-linux-gnu/lib, racer already installed but I cannot understand how to create a rust project.

**Comment by dghilardi** [comment]
Right now the plugin only deals with autocompletion tasks. I suggest you to create a rust project with the command line:

``` sh
cargo new hello_world --bin
```

and import in qtcreator via file > New file or project > Import project > import existing project.
Then you should manually configure the project with 'cargo run' as build step (in the projects>Build view) and point to the right executable file (in the projects>run view).
You may also want to enable the syntax highlighting by enabling the generic syntax highlighter for rust in tools>options>Text Editor>generic highlighter>Download definitions... and restarting qtcreator.
Btw I have some ideas about the integration of the project management inside the plugin, I hope to find a way to integrate them into the plugin soon.

**Comment by Mte90** [comment]
Interesting, add that steps in the readme to help other users?
